### ISSUE TITLE
filehandling rules: allow for an explicit directive to just use the original file

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#153]
Should be something like:
```YAML
default:
    storage:
        location: internal
        representation: None 
```
Currently that is more or less the default
