### ISSUE TITLE
migration: alter() fails if datatype changed from boolean to int. Needs a cast.

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#381]
That's the dsd for table constants:

```
constants:
  meta:
    flags: [export_dont_truncate]
    import_filter:
      fm12: "(sync is null) or (sync)"
  structure:
    2:
      id: [datatype(VARCHAR)]
      value: [datatype(VARCHAR)]
      value_ts: [datatype(TIMESTAMP)]
      category: [datatype(VARCHAR)]
      comment: [datatype(VARCHAR)]
      field_type: [datatype(VARCHAR)]
      sync: [datatype(NUMBER), default(1)]
      uid: [datatype(UUID), replfield_uuid()]
      created: [datatype(TIMESTAMP), replfield_created()]
      modified: [datatype(TIMESTAMP), replfield_modified()]
      modified_by: [datatype(VARCHAR), replfield_modified_by(), default('Null')]
    1:
      id: [datatype(VARCHAR)]
      value: [datatype(VARCHAR)]
      value_ts: [datatype(TIMESTAMP)]
      category: [datatype(VARCHAR)]
      comment: [datatype(VARCHAR)]
      field_type: [datatype(VARCHAR)]
      sync: [datatype(BOOLEAN), default(True)]
      uid: [datatype(UUID), replfield_uuid()]
      created: [datatype(TIMESTAMP), replfield_created()]
      modified: [datatype(TIMESTAMP), replfield_modified()]
      modified_by: [datatype(VARCHAR), replfield_modified_by(), default('Null')]
  migration:
    2:
      upgrade:
      - alter("sync")
```
