### ISSUE TITLE
USTP and khpp kiosk configuration needs recording_context_aliases

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#802]
something like this is needed in the kiosk_config:

```
file_repostiory:
  recording_context_aliases:
    locus: "context"
    unit: "trench/area"
    locus_photo: "context"
    dayplan: "trench/area"
    locus_relations: "context relations"
    collected_material_photo: "collected material & small finds"
    site_note_photo: "site note"
    site: "site map"
    pottery_images: "pottery"
    tags: "context tags"

```
