### ISSUE TITLE
KioskContext.select does not allow for more than one field with the same instruction per record type

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#856]
I the dsd defines a record type e.g. with two identifiers like this:

```
collected_material:
  structure:
    2:
      external_id: [datatype(VARCHAR), identifier()]
      arch_context: [datatype(VARCHAR), identifier()]

```
and there is a context definition that includes this table and a select statement that uses "identifier()" either as primary field_or_instruction or as additional field, select throws a KioskContextDuplicateInstructionError.

There might be scenarios where that is not what we want.
Since the whole select fails, would it make sense to have the option to at least ignore the issue in a first step?
